# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'hack_11'
  app.vendor_project('vendor/AsyncSocket', :xcode, :headers_dir => 'AsyncSocket')
  app.frameworks << 'CFNetwork'
end
